// AUTO-GENERATED by scripts/calibrate-exercises.ts — do not edit by hand.
export interface CalibratedTarget {
  f1: number;
  f2: number;
  attribution: string;
  audio: string;
}
export const CALIBRATED: Record<string, CalibratedTarget> = {
  "my": {
    "f1": 367,
    "f2": 1489,
    "attribution": "Сергей Сахно, Vion Nicolas / CC BY 3.0 us — File:Ru-мы.ogg, Wikimedia Commons",
    "audio": "audio/exercises/my.ogg"
  },
  "ty": {
    "f1": 350,
    "f2": 1500,
    "attribution": "Сергей Сахно, Vion Nicolas / CC BY 3.0 us — File:Ru-ты.ogg, Wikimedia Commons",
    "audio": "audio/exercises/ty.ogg"
  },
  "vy": {
    "f1": 350,
    "f2": 1504,
    "attribution": "Сергей Сахно, Vion Nicolas / CC BY 3.0 us — File:Ru-вы.ogg, Wikimedia Commons",
    "audio": "audio/exercises/vy.ogg"
  },
  "syn": {
    "f1": 264,
    "f2": 1525,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-сын.ogg, Wikimedia Commons",
    "audio": "audio/exercises/syn.ogg"
  },
  "syr": {
    "f1": 303,
    "f2": 1646,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-сыр.ogg, Wikimedia Commons",
    "audio": "audio/exercises/syr.ogg"
  },
  "dym": {
    "f1": 350,
    "f2": 1500,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-дым.ogg, Wikimedia Commons",
    "audio": "audio/exercises/dym.ogg"
  },
  "byk": {
    "f1": 314,
    "f2": 1599,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-бык.ogg, Wikimedia Commons",
    "audio": "audio/exercises/byk.ogg"
  },
  "ryba": {
    "f1": 344,
    "f2": 1579,
    "attribution": "Gulnara Streit / CC BY 2.0 fr — File:Ru-рыба.ogg, Wikimedia Commons",
    "audio": "audio/exercises/ryba.ogg"
  },
  "mysh": {
    "f1": 272,
    "f2": 1378,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-мышь.ogg, Wikimedia Commons",
    "audio": "audio/exercises/mysh.ogg"
  },
  "mylo": {
    "f1": 333,
    "f2": 1466,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-мыло.ogg, Wikimedia Commons",
    "audio": "audio/exercises/mylo.ogg"
  },
  "yazyk": {
    "f1": 299,
    "f2": 1752,
    "attribution": "Wikimedia Commons / CC BY 2.0 fr — File:Ru-язык.ogg, Wikimedia Commons",
    "audio": "audio/exercises/yazyk.ogg"
  }
};
